apiVersion: v1
kind: Service
metadata:
  name: socket-service
spec:
  type: NodePort
  selector:
    app: socket-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
