name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Navigate to app folder
            cd Socket.io

            # Pull latest changes
            git fetch origin
            git reset --hard origin/master

            # Stop and remove old container on port 3000 if exists
            OLD_CONTAINER=$(sudo docker ps -q --filter "publish=3000")
            if [ ! -z "$OLD_CONTAINER" ]; then
              sudo docker stop $OLD_CONTAINER
              sudo docker rm $OLD_CONTAINER
            fi

            # Build and run new container
            sudo docker build -t socket .
            sudo docker run -d --name socket-container -p 3000:3000 socket
          EOF
