name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
            cd Socket.io || exit 1

            # Reset to latest code from GitHub
            git fetch origin master
            git reset --hard origin/master

            # Stop and remove container if exists
            sudo docker stop socket-container || true
            sudo docker rm socket-container || true

            # Kill anything running on port 3000
            port_pid=\$(sudo lsof -t -i:3000)
            if [ ! -z "\$port_pid" ]; then
              sudo kill -9 \$port_pid
            fi

            # Build and run Docker container
            sudo docker build -t socket .
            sudo docker run -d --name socket-container -p 3000:3000 socket
          EOF
